Wrapping mapbox js components
Lyddon7522/KeepItClean pull request #14
Opened 2023-03-20 15:45 UTC by Lyddon7522

2023-03-20 16:43 UTC, benjaminsampica requested changes

2023-03-20 16:43 UTC, benjaminsampica commented on src/Samsons.BlazorMaps.MapBox/Components/Map/Map.razor.js
> +    try {
Plz delete

2023-03-20 17:07 UTC, Lyddon7522 commented
I've got a couple of those to do. Meant to mark as a draft and failed miserably at that. Same for the MapOptions file, it has all the possible options, but we aren't using them so I'm going to pull those out.

2023-03-20 17:10 UTC, Lyddon7522 commented on src/Samsons.BlazorMaps.MapBox/Components/Map/Map.razor.js
> +    try {
fixed

2023-03-24 01:51 UTC, benjaminsampica approved these changes

2023-03-24 01:51 UTC, merged